name: Protect main branch
enforcement: active
bypass_actors: ['user:AriBermeki']
conditions:
  ref_name:
    include:
      - "refs/heads/main"

rules:
  - type: deletion
    parameters: {}
  - type: non_fast_forward
    parameters: {}
  - type: linear_history
    parameters: {}
  - type: required_pull_request
    parameters:
      required_approving_review_count: 1
      require_code_owner_review: false
      dismiss_stale_reviews_on_push: true
      require_last_push_approval: false
      required_review_thread_resolution: true
  - type: required_status_checks
    parameters:
      strict_required_status_checks_policy: true
      required_status_checks:
        - "docs"
        - "test"
        - "lint"
  - type: merge_queue
    parameters: {}
  - type: allowed_merge_methods
    parameters:
      merge_commit: false
      squash: true
      rebase: true
